#!/usr/bin/env bash
# Installer for PDF toolchain (macOS / Linux)
# - Checks/installs Python 3 (best-effort)
# - Creates a local virtualenv .venv/
# - Installs PDF libraries
# - Creates a launcher in ~/.local/bin/resume-build that runs resume.py from this project
# Notes:
#   - Run this script from your project root.
#   - If Homebrew/apt is unavailable, you may need to install Python manually.

set -euo pipefail

PROJECT_ROOT="$(pwd)"
INSTALL_BIN="${HOME}/.local/bin"
LAUNCHER="${INSTALL_BIN}/resume-build"

echo "[1/6] Checking Python 3..."
if ! command -v python3 >/dev/null 2>&1; then
  OS="$(uname -s || true)"
  if [[ "$OS" == "Darwin" ]]; then
    echo "Python 3 not found. Attempting Homebrew install..."
    if ! command -v brew >/dev/null 2>&1; then
      echo "Homebrew not found. Install Homebrew or Python 3 manually and re-run."
      exit 1
    fi
    brew install python
  else
    # Attempt apt-based install; otherwise ask user to install manually.
    if command -v apt-get >/dev/null 2>&1; then
      echo "Python 3 not found. Installing via apt..."
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-venv python3-pip
    else
      echo "Python 3 not found and no automatic installer is available for this distro."
      echo "Please install Python 3, then re-run this script."
      exit 1
    fi
  fi
fi

echo "[2/6] Creating virtual environment: .venv"
if [[ ! -d ".venv" ]]; then
  python3 -m venv .venv
fi

echo "[3/6] Upgrading pip"
. .venv/bin/activate
python -m pip install --upgrade pip wheel setuptools

echo "[4/6] Installing PDF libraries"
# reportlab: create PDFs
# pypdf2: merge/split/rotate etc.
# pdfminer.six + pdfplumber: text extraction
# Pillow: images
# PyYAML, click: config + CLI convenience
python -m pip install \
  reportlab \
  pypdf2 \
  pdfminer.six \
  pdfplumber \
  pillow \
  PyYAML \
  click

deactivate

echo "[5/6] Creating launcher: ${LAUNCHER}"
mkdir -p "${INSTALL_BIN}"
cat > "${LAUNCHER}" <<'EOF'
#!/usr/bin/env bash
# Wrapper to run resume.py from the project where it was installed.
# This file is generated by install_unix.sh.

set -euo pipefail

PROJECT_ROOT="__PROJECT_ROOT__"
VENV="${PROJECT_ROOT}/.venv"
PY="${VENV}/bin/python"

if [[ ! -x "${PY}" ]]; then
  echo "Virtualenv not found at ${VENV}. Re-run install_unix.sh." >&2
  exit 1
fi

# Forward all arguments to your generator script.
exec "${PY}" "${PROJECT_ROOT}/resume.py" "$@"
EOF

# Replace placeholder with current project path (escape slashes)
ESCAPED_ROOT=$(printf '%s' "$PROJECT_ROOT" | sed 's/[\/&]/\\&/g')
sed -i.bak "s/__PROJECT_ROOT__/${ESCAPED_ROOT}/g" "${LAUNCHER}" && rm -f "${LAUNCHER}.bak"
chmod +x "${LAUNCHER}"

echo "[6/6] Ensuring ${INSTALL_BIN} is in PATH"
case ":$PATH:" in
  *":${INSTALL_BIN}:"*) echo "PATH already contains ${INSTALL_BIN}";;
  *)
    SHELL_RC="${HOME}/.profile"
    if [[ -n "${ZSH_VERSION-}" ]]; then SHELL_RC="${HOME}/.zshrc"; fi
    if [[ -n "${BASH_VERSION-}" ]]; then SHELL_RC="${HOME}/.bashrc"; fi
    echo "export PATH=\"${INSTALL_BIN}:\$PATH\"" >> "${SHELL_RC}"
    echo "Added ${INSTALL_BIN} to PATH in ${SHELL_RC}. Open a new terminal or run: source ${SHELL_RC}"
    ;;
esac

echo "Done."
echo "Usage example:"
echo "  resume-build --help"